language: go

go:
  - 1.11.x

sudo: required
services:
  - docker

jobs:
  include:
    - stage: test
      script: go test -v ./backend/src/app
    - stage: build
      script:
      - docker build -t blog-frontend ./frontend
      - docker build -t blog-backend ./backend

notifications:
  email: false