version: '3'
services: 
  backend:
    image: martinheinz/blog_backend:latest
    build: 
      context: ./backend
      dockerfile: ./Dockerfile
    healthcheck:
        test: ["CMD", "curl", "-f", "backend"]
        interval: 30s
        timeout: 10s
        retries: 5

  frontend:
    image: martinheinz/blog_frontend:latest
    build: 
      context: ./frontend
      dockerfile: ./Dockerfile
    depends_on: 
      - backend
    ports:
      - 8080:8080
